### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by didiercedric** [didiercedric/TSP-Optimization#3]
/tsp2.py

- Optimization
- Overall review

**Comment by wafaajaunnoo** [comment]
utACK!
i went through it really quickly, just make sure to include these:
1. vectorized operations instead of loops
2. Cython or Numba for further optimization
3. keep your code DRY, avoid redundant calc
4. pre-compute constants

**Comment by didiercedric** [comment]
Thanks a lot man
